### ISSUE TITLE
Intro to iOS Code Path Project

### ISSUE THREAD

**Issue by kowongh** [kowongh/CodePathIntroToiOS#1]
My app is done. Please take a look. Thanks! I look forward to hearing from you. /cc @codepathreview

**Comment by kowongh** [comment]
I've just extended my app, improved the UI and extended the features! I finished the first portion this morning, then I had to go to work and finished this later in the evening. Thank you.
/cc @codepathreview

**Comment by codepathreview** [comment]
Hi Korin,
Thanks for submitting your pre-work but your current submission is incomplete. Can you please review the section in the pre-work about [the readme]https://courses.codepath.com/snippets/intro_to_ios/prework.md#heading-5-submitting-the-project) for your project? 

In particular, be sure to start from the README template that is linked there, check off your completed required and optional features (`[x]`), list any additional features, and [include a recorded app walkthrough with LiceCap](http://www.cockos.com/licecap/). 

Please re-submit your project on your [application dashboard](https://apply.codepath.com/dashboard/), and it will notify us to review again.
